language: scala
scala:
  - 2.13.5

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier/cache
    - $HOME/.cache/coursier
    - sysconfcpus

install:
  - TRAVIS_NODE_VERSION="10" nvm install node
  - nvm use node
  - node --version
  - npm --version
  - npm install -g elm
  - |
    # update this only when sbt-the-bash-script needs to be updated
    export SBT_LAUNCHER=1.4.8
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt

before_script:
  - export TZ=Europe/Berlin

script:
  - sbt -J-XX:+UseG1GC ++$TRAVIS_SCALA_VERSION ci
