language: scala
scala:
  - 2.13.5

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.coursier/cache
    - $HOME/.cache/coursier
    - sysconfcpus

install:
  - TRAVIS_NODE_VERSION="10" nvm install node
  - nvm use node
  - node --version
  - npm --version
  - npm install -g elm

before_script:
  - export TZ=Europe/Berlin

script:
  - sbt -J-XX:+UseG1GC ++$TRAVIS_SCALA_VERSION ";project root ;scalafmtCheckAll ;make ;test"
